"use client";
import Link from 'next/link';

export default function HowItWorks() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#030617' }}>
      {/* Hero Section */}
      <div className="py-16" style={{ backgroundColor: '#030617' }}>
        <div className="container mx-auto px-4 text-center">
          <h1 className="mb-4 text-4xl font-bold tracking-tight md:text-5xl" style={{ color: '#91c9a6' }}>
            How GrokCII Works
          </h1>
          <p className="mx-auto max-w-2xl text-lg text-white">
            Discover how GrokCII combines AI-generated ASCII art with wallet addresses
            to create unique personalized characters.
          </p>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto max-w-4xl px-4 py-12">
        <div className="grid gap-12">
          {/* Character Generation Section */}
          <section className="overflow-hidden rounded-xl border border-[#91c9a6] shadow-lg" style={{ backgroundColor: '#030617' }}>
            <div className="border-b border-[#91c9a6] p-4">
              <div className="flex items-center">
                <div className="mr-3 flex h-8 w-8 items-center justify-center rounded-full bg-[#91c9a6]/20">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="#91c9a6" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 2a4 4 0 0 1 4 4c0 1.95-1.4 3.58-3 3.92v1.58h5a3 3 0 0 1 3 3v1.5M12 2a4 4 0 0 0-4 4c0 1.95 1.4 3.58 3 3.92v1.58H6a3 3 0 0 0-3 3v1.5M19 16l-2 3h4l-2 3M2 19h5"></path>
                  </svg>
                </div>
                <h2 className="text-2xl font-bold" style={{ color: '#91c9a6' }}>Character Generation</h2>
              </div>
            </div>
            
            <div className="p-6">
              <p className="mb-6 leading-relaxed text-white/90">
                Every wallet connected to GrokCII automatically receives a unique ASCII character generated by Grok AI. 
                This character is permanently linked to your wallet address and stored in our database.
              </p>
              
              <div className="mb-8 grid gap-6 md:grid-cols-2">
                <div className="rounded-lg border border-[#91c9a6] p-5" style={{ backgroundColor: '#030617' }}>
                  <h3 className="mb-3 flex items-center text-lg font-semibold" style={{ color: '#91c9a6' }}>
                    <span className="mr-2 flex h-6 w-6 items-center justify-center rounded-full bg-[#91c9a6]/20 text-xs">1</span>
                    The Generation Process
                  </h3>
                  <ol className="ml-4 space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>When you connect your wallet for the first time, our system checks if you already have a character</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>If no character exists, we send a request to Grok AI with a carefully crafted prompt</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Grok AI generates a unique fantasy character with a name, ASCII art representation, and backstory</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>The character is saved to our database and associated with your wallet address</span>
                    </li>
                  </ol>
                </div>
                
                <div className="rounded-lg border border-[#91c9a6] p-5" style={{ backgroundColor: '#030617' }}>
                  <h3 className="mb-3 flex items-center text-lg font-semibold" style={{ color: '#91c9a6' }}>
                    <span className="mr-2 flex h-6 w-6 items-center justify-center rounded-full bg-[#91c9a6]/20 text-xs">2</span>
                    The Prompt We Use
                  </h3>
                  <div className="mb-3 rounded bg-black/50 p-3 font-mono text-sm text-[#91c9a6]/90">
                    <pre className="whitespace-pre-wrap">{`Generate a unique fantasy character with the following:
1. A creative fantasy name
2. An ASCII art representation of the character (maximum 20 lines)
3. A short backstory (2-3 sentences)

Format the response exactly like this:
NAME: [character name]
ASCII:
[ASCII art]
STORY: [character backstory]`}</pre>
                  </div>
                  <p className="text-sm text-white/80">
                    We use a temperature setting of 0.9 to ensure high creativity and uniqueness for each character.
                  </p>
                </div>
              </div>
              
              <div className="rounded-lg border border-[#91c9a6] p-4" style={{ backgroundColor: '#030617' }}>
                <div className="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" className="mr-2 h-5 w-5 text-[#91c9a6]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="12" y1="8" x2="12" y2="12"></line>
                    <line x1="12" y1="16" x2="12.01" y2="16"></line>
                  </svg>
                  <span className="font-medium text-[#91c9a6]">Did you know?</span>
                </div>
                <p className="mt-2 text-sm text-white/80">
                  Each character is completely unique. Even if two users have similar ASCII art, the combination of name, art, and backstory ensures that no two characters are exactly alike.
                </p>
              </div>
            </div>
          </section>
          
          {/* Tokenization Section */}
          <section className="overflow-hidden rounded-xl border border-[#91c9a6] shadow-lg" style={{ backgroundColor: '#030617' }}>
            <div className="border-b border-[#91c9a6] p-4">
              <div className="flex items-center">
                <div className="mr-3 flex h-8 w-8 items-center justify-center rounded-full bg-[#91c9a6]/20">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="#91c9a6" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path>
                    <path d="M12 18V6"></path>
                  </svg>
                </div>
                <h2 className="text-2xl font-bold" style={{ color: '#91c9a6' }}>Tokenization</h2>
              </div>
            </div>
            
            <div className="p-6">
              <p className="mb-6 leading-relaxed text-white/90">
                GrokCII allows you to tokenize your character by linking it to an SPL token on the Solana blockchain. 
                This creates a connection between your unique character and a tradable token, allowing you to participate in the wider ecosystem.
              </p>
              
              <div className="mb-8 grid gap-6 md:grid-cols-2">
                <div className="rounded-lg border border-[#91c9a6] p-5" style={{ backgroundColor: '#030617' }}>
                  <h3 className="mb-3 flex items-center text-lg font-semibold" style={{ color: '#91c9a6' }}>
                    <span className="mr-2 flex h-6 w-6 items-center justify-center rounded-full bg-[#91c9a6]/20 text-xs">1</span>
                    How to Tokenize Your Character
                  </h3>
                  <ol className="ml-4 space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Create an SPL token on Solana (using tools like Pump.fun)</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Go to the <Link href="/tokenize" className="text-[#91c9a6] underline hover:text-white">Tokenize page</Link> on GrokCII</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Enter your SPL token address in the form</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Submit the form to link your character to the token</span>
                    </li>
                  </ol>
                  <p className="mt-3 text-sm text-white/80">
                    Once tokenized, your character will appear in the "Tokenized Characters" section, and you can click on it to view it on Pump.fun.
                  </p>
                </div>
                
                <div className="rounded-lg border border-[#91c9a6] p-5" style={{ backgroundColor: '#030617' }}>
                  <h3 className="mb-3 flex items-center text-lg font-semibold" style={{ color: '#91c9a6' }}>
                    <span className="mr-2 flex h-6 w-6 items-center justify-center rounded-full bg-[#91c9a6]/20 text-xs">2</span>
                    Benefits of Tokenization
                  </h3>
                  <ul className="ml-4 space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Create a tradable asset based on your unique character</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Join the growing ecosystem of Solana-based ASCII art tokens</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Showcase your character's uniqueness and rarity</span>
                    </li>
                    <li className="flex items-start">
                      <span className="mr-2 mt-1 text-[#91c9a6]">•</span>
                      <span>Connect with other GrokCII character owners</span>
                    </li>
                  </ul>
                </div>
              </div>
              
              <div className="rounded-lg border border-[#91c9a6] p-4" style={{ backgroundColor: '#030617' }}>
                <div className="flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" className="mr-2 h-5 w-5 text-[#91c9a6]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                  </svg>
                  <span className="font-medium text-[#91c9a6]">Security Note</span>
                </div>
                <p className="mt-2 text-sm text-white/80">
                  Your character data is stored securely in our database. The tokenization process only creates a link between your character and the SPL token - it doesn't transfer ownership of your character data.
                </p>
              </div>
            </div>
          </section>
          
          {/* Empty space for padding */}
          <div className="h-8"></div>
        </div>
      </div>
    </div>
  );
}
